/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_me_retrieve"];
        put: operations["auth_me_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["auth_me_partial_update"];
        trace?: never;
    };
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["customers_list"];
        put?: never;
        post: operations["customers_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["customers_retrieve"];
        put: operations["customers_update"];
        post?: never;
        delete: operations["customers_destroy"];
        options?: never;
        head?: never;
        patch: operations["customers_partial_update"];
        trace?: never;
    };
    "/api/livraisons/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["livraisons_list"];
        put?: never;
        post: operations["livraisons_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/livraisons/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["livraisons_retrieve"];
        put: operations["livraisons_update"];
        post?: never;
        delete: operations["livraisons_destroy"];
        options?: never;
        head?: never;
        patch: operations["livraisons_partial_update"];
        trace?: never;
    };
    "/api/paiements/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["paiements_list"];
        put?: never;
        post: operations["paiements_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paiements/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["paiements_retrieve"];
        put: operations["paiements_update"];
        post?: never;
        delete: operations["paiements_destroy"];
        options?: never;
        head?: never;
        patch: operations["paiements_partial_update"];
        trace?: never;
    };
    "/api/product-categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["product_categories_list"];
        put?: never;
        post: operations["product_categories_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product-categories/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["product_categories_retrieve"];
        put: operations["product_categories_update"];
        post?: never;
        delete: operations["product_categories_destroy"];
        options?: never;
        head?: never;
        patch: operations["product_categories_partial_update"];
        trace?: never;
    };
    "/api/products/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["products_list"];
        put?: never;
        post: operations["products_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["products_retrieve"];
        put: operations["products_update"];
        post?: never;
        delete: operations["products_destroy"];
        options?: never;
        head?: never;
        patch: operations["products_partial_update"];
        trace?: never;
    };
    "/api/roles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["roles_list"];
        put?: never;
        post: operations["roles_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["roles_retrieve"];
        put: operations["roles_update"];
        post?: never;
        delete: operations["roles_destroy"];
        options?: never;
        head?: never;
        patch: operations["roles_partial_update"];
        trace?: never;
    };
    "/api/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/assign_role/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["users_assign_role_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/remove_role/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["users_remove_role_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ventes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ventes_list"];
        put?: never;
        post: operations["ventes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ventes/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ventes_retrieve"];
        put: operations["ventes_update"];
        post?: never;
        delete: operations["ventes_destroy"];
        options?: never;
        head?: never;
        patch: operations["ventes_partial_update"];
        trace?: never;
    };
    "/api/ventes/{id}/annuler/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ventes_annuler_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ventes/{id}/valider/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ventes_valider_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `MGA` - Ariary malgache
         *     * `EUR` - Euro
         *     * `USD` - Dollar américain
         * @enum {string}
         */
        CurrencyEnum: "MGA" | "EUR" | "USD";
        Customer: {
            readonly id: string;
            name: string;
            email?: string;
            phone?: string;
            address?: string;
            city?: string;
            /** Format: date */
            birth_date?: string | null;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        Livraison: {
            readonly id: string;
            vente: string;
            status?: components["schemas"]["LivraisonStatusEnum"];
            /** Format: date */
            delivery_date?: string | null;
            address?: string;
            tracking_number?: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `pending` - En attente
         *     * `shipped` - Expédiée
         *     * `delivered` - Livrée
         * @enum {string}
         */
        LivraisonStatusEnum: "pending" | "shipped" | "delivered";
        /**
         * @description * `cash` - Espèces
         *     * `card` - Carte
         *     * `transfer` - Virement
         * @enum {string}
         */
        MethodEnum: "cash" | "card" | "transfer";
        PaginatedCustomerList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Customer"][];
        };
        PaginatedLivraisonList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Livraison"][];
        };
        PaginatedPaiementList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Paiement"][];
        };
        PaginatedProductCategoryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ProductCategory"][];
        };
        PaginatedProductReadList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ProductRead"][];
        };
        PaginatedRoleList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Role"][];
        };
        PaginatedUserListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["UserList"][];
        };
        PaginatedVenteReadList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["VenteRead"][];
        };
        Paiement: {
            readonly id: string;
            vente: string;
            /** Format: decimal */
            amount: string;
            method?: components["schemas"]["MethodEnum"];
            /** Format: date-time */
            paid_at?: string;
            reference?: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        PatchedCustomer: {
            readonly id?: string;
            name?: string;
            email?: string;
            phone?: string;
            address?: string;
            city?: string;
            /** Format: date */
            birth_date?: string | null;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedLivraison: {
            readonly id?: string;
            vente?: string;
            status?: components["schemas"]["LivraisonStatusEnum"];
            /** Format: date */
            delivery_date?: string | null;
            address?: string;
            tracking_number?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedPaiement: {
            readonly id?: string;
            vente?: string;
            /** Format: decimal */
            amount?: string;
            method?: components["schemas"]["MethodEnum"];
            /** Format: date-time */
            paid_at?: string;
            reference?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        /**
         * @description Write-only path (`create`/`update`) — `ProductViewSet.list`/`retrieve`
         *     use `ProductReadSerializer` (backed by the `ProductListView` DB view)
         *     instead, so this doesn't need a `category_name` resolved field.
         */
        PatchedProduct: {
            readonly id?: string;
            name?: string;
            sku?: string;
            /** Format: decimal */
            default_price?: string;
            category?: string | null;
            description?: string;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedProductCategory: {
            readonly id?: string;
            name?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedRole: {
            readonly id?: string;
            name?: string;
            permissions?: string[];
        };
        PatchedUser: {
            readonly id?: string;
            readonly username?: string;
            email?: string;
            first_name?: string;
            last_name?: string;
            readonly roles?: string[];
            readonly permissions?: string[];
        };
        /**
         * @description Write-only path (`create`/`update`) — `VenteViewSet.list`/`retrieve`
         *     use `VenteReadSerializer` (backed by the `VenteListView` DB view)
         *     instead, so this doesn't need a `customer_name` resolved field.
         */
        PatchedVente: {
            readonly id?: string;
            customer?: string;
            readonly status?: components["schemas"]["VenteStatusEnum"];
            priority?: components["schemas"]["PriorityEnum"];
            currency?: components["schemas"]["CurrencyEnum"];
            /** Format: decimal */
            discount_percent?: string;
            /** Format: decimal */
            readonly subtotal_ht?: string;
            /** Format: decimal */
            readonly discount_amount?: string;
            /** Format: decimal */
            readonly tva_amount?: string;
            /** Format: decimal */
            readonly total?: string;
            /** Format: date */
            expected_delivery_date?: string | null;
            notes?: string;
            lines?: components["schemas"]["VenteLigne"][];
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        /**
         * @description * `low` - Basse
         *     * `normal` - Normale
         *     * `high` - Haute
         * @enum {string}
         */
        PriorityEnum: "low" | "normal" | "high";
        /**
         * @description Write-only path (`create`/`update`) — `ProductViewSet.list`/`retrieve`
         *     use `ProductReadSerializer` (backed by the `ProductListView` DB view)
         *     instead, so this doesn't need a `category_name` resolved field.
         */
        Product: {
            readonly id: string;
            name: string;
            sku: string;
            /** Format: decimal */
            default_price?: string;
            category?: string | null;
            description?: string;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        ProductCategory: {
            readonly id: string;
            name: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description Backed by `ProductListView` (DB view) — used for `list`/`retrieve`
         *     only (`ProductViewSet.get_serializer_class`). `category_name` comes
         *     from the view's join; `create`/`update`/`destroy` go through the
         *     writable `Product` model + `ProductSerializer` instead.
         */
        ProductRead: {
            id: string;
            name: string;
            sku: string;
            /** Format: decimal */
            default_price: string;
            category?: string | null;
            category_name?: string | null;
            description: string;
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Register: {
            readonly id: string;
            username: string;
            email?: string;
            password: string;
        };
        Role: {
            readonly id: string;
            name: string;
            permissions?: string[];
        };
        TokenObtainPair: {
            username: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        User: {
            readonly id: string;
            readonly username: string;
            email?: string;
            first_name?: string;
            last_name?: string;
            readonly roles: string[];
            readonly permissions: string[];
        };
        UserList: {
            readonly id: string;
            readonly username: string;
            /** Format: email */
            readonly email: string;
            readonly is_active: boolean;
            readonly is_staff: boolean;
            readonly roles: string[];
        };
        /**
         * @description Write-only path (`create`/`update`) — `VenteViewSet.list`/`retrieve`
         *     use `VenteReadSerializer` (backed by the `VenteListView` DB view)
         *     instead, so this doesn't need a `customer_name` resolved field.
         */
        Vente: {
            readonly id: string;
            customer: string;
            readonly status: components["schemas"]["VenteStatusEnum"];
            priority?: components["schemas"]["PriorityEnum"];
            currency?: components["schemas"]["CurrencyEnum"];
            /** Format: decimal */
            discount_percent?: string;
            /** Format: decimal */
            readonly subtotal_ht: string;
            /** Format: decimal */
            readonly discount_amount: string;
            /** Format: decimal */
            readonly tva_amount: string;
            /** Format: decimal */
            readonly total: string;
            /** Format: date */
            expected_delivery_date?: string | null;
            notes?: string;
            lines: components["schemas"]["VenteLigne"][];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description Write-only path, nested in `VenteSerializer` — `product_name`/
         *     `product_sku` aren't needed here, `VenteLigneReadSerializer` (backed by
         *     the `VenteLigneListView` DB view) carries those for `list`/`retrieve`.
         */
        VenteLigne: {
            id?: string;
            product: string;
            /** Format: decimal */
            quantity: string;
            /** Format: decimal */
            unit_price: string;
            /** Format: decimal */
            discount_percent?: string;
            /** Format: decimal */
            tva_rate?: string;
        };
        /**
         * @description Backed by `VenteLigneListView` (DB view) — `product_name`/`product_sku`
         *     come from the view's join, not a per-request lookup or a client-side
         *     fetch-everything-and-resolve.
         */
        VenteLigneRead: {
            id: string;
            product: string;
            product_name: string;
            product_sku: string;
            /** Format: decimal */
            quantity: string;
            /** Format: decimal */
            unit_price: string;
            /** Format: decimal */
            discount_percent: string;
            /** Format: decimal */
            tva_rate: string;
        };
        /**
         * @description Backed by `VenteListView` (DB view) — used for `list`/`retrieve` only
         *     (`VenteViewSet.get_serializer_class`). `customer_name` comes from the
         *     view's join; `create`/`update`/`valider`/`annuler` go through the
         *     writable `Vente` model + `VenteSerializer` instead.
         */
        VenteRead: {
            id: string;
            customer: string;
            customer_name: string;
            status: string;
            priority: string;
            currency: string;
            /** Format: decimal */
            discount_percent: string;
            /** Format: decimal */
            subtotal_ht: string;
            /** Format: decimal */
            discount_amount: string;
            /** Format: decimal */
            tva_amount: string;
            /** Format: decimal */
            total: string;
            /** Format: date */
            expected_delivery_date?: string | null;
            notes: string;
            readonly lines: components["schemas"]["VenteLigneRead"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description * `draft` - Brouillon
         *     * `validated` - Validée
         *     * `cancelled` - Annulée
         * @enum {string}
         */
        VenteStatusEnum: "draft" | "validated" | "cancelled";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_me_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["User"];
                "application/x-www-form-urlencoded": components["schemas"]["User"];
                "multipart/form-data": components["schemas"]["User"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUser"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUser"];
                "multipart/form-data": components["schemas"]["PatchedUser"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Register"];
                "application/x-www-form-urlencoded": components["schemas"]["Register"];
                "multipart/form-data": components["schemas"]["Register"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Register"];
                };
            };
        };
    };
    customers_list: {
        parameters: {
            query?: {
                /** @description Les valeurs multiples doivent être séparées par des virgules. */
                city?: string[];
                email?: string;
                is_active?: boolean;
                name?: string;
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
                /** @description Un numéro de page de l'ensemble des résultats. */
                page?: number;
                /** @description Nombre de résultats à retourner par page. */
                page_size?: number;
                /** @description Un terme de recherche. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCustomerList"];
                };
            };
        };
    };
    customers_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Customer"];
                "application/x-www-form-urlencoded": components["schemas"]["Customer"];
                "multipart/form-data": components["schemas"]["Customer"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
        };
    };
    customers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) customer. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
        };
    };
    customers_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) customer. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Customer"];
                "application/x-www-form-urlencoded": components["schemas"]["Customer"];
                "multipart/form-data": components["schemas"]["Customer"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
        };
    };
    customers_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) customer. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    customers_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) customer. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCustomer"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCustomer"];
                "multipart/form-data": components["schemas"]["PatchedCustomer"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
        };
    };
    livraisons_list: {
        parameters: {
            query?: {
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
                /** @description Un numéro de page de l'ensemble des résultats. */
                page?: number;
                /** @description Nombre de résultats à retourner par page. */
                page_size?: number;
                /** @description Un terme de recherche. */
                search?: string;
                /** @description Les valeurs multiples doivent être séparées par des virgules. */
                status?: string[];
                vente?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLivraisonList"];
                };
            };
        };
    };
    livraisons_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Livraison"];
                "application/x-www-form-urlencoded": components["schemas"]["Livraison"];
                "multipart/form-data": components["schemas"]["Livraison"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Livraison"];
                };
            };
        };
    };
    livraisons_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) livraison. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Livraison"];
                };
            };
        };
    };
    livraisons_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) livraison. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Livraison"];
                "application/x-www-form-urlencoded": components["schemas"]["Livraison"];
                "multipart/form-data": components["schemas"]["Livraison"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Livraison"];
                };
            };
        };
    };
    livraisons_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) livraison. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    livraisons_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) livraison. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedLivraison"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedLivraison"];
                "multipart/form-data": components["schemas"]["PatchedLivraison"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Livraison"];
                };
            };
        };
    };
    paiements_list: {
        parameters: {
            query?: {
                /** @description Les valeurs multiples doivent être séparées par des virgules. */
                method?: string[];
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
                /** @description Un numéro de page de l'ensemble des résultats. */
                page?: number;
                /** @description Nombre de résultats à retourner par page. */
                page_size?: number;
                /** @description Un terme de recherche. */
                search?: string;
                vente?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPaiementList"];
                };
            };
        };
    };
    paiements_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Paiement"];
                "application/x-www-form-urlencoded": components["schemas"]["Paiement"];
                "multipart/form-data": components["schemas"]["Paiement"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paiement"];
                };
            };
        };
    };
    paiements_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) paiement. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paiement"];
                };
            };
        };
    };
    paiements_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) paiement. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Paiement"];
                "application/x-www-form-urlencoded": components["schemas"]["Paiement"];
                "multipart/form-data": components["schemas"]["Paiement"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paiement"];
                };
            };
        };
    };
    paiements_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) paiement. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    paiements_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) paiement. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPaiement"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPaiement"];
                "multipart/form-data": components["schemas"]["PatchedPaiement"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paiement"];
                };
            };
        };
    };
    product_categories_list: {
        parameters: {
            query?: {
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
                /** @description Un numéro de page de l'ensemble des résultats. */
                page?: number;
                /** @description Nombre de résultats à retourner par page. */
                page_size?: number;
                /** @description Un terme de recherche. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProductCategoryList"];
                };
            };
        };
    };
    product_categories_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCategory"];
                "application/x-www-form-urlencoded": components["schemas"]["ProductCategory"];
                "multipart/form-data": components["schemas"]["ProductCategory"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductCategory"];
                };
            };
        };
    };
    product_categories_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) product category. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductCategory"];
                };
            };
        };
    };
    product_categories_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) product category. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCategory"];
                "application/x-www-form-urlencoded": components["schemas"]["ProductCategory"];
                "multipart/form-data": components["schemas"]["ProductCategory"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductCategory"];
                };
            };
        };
    };
    product_categories_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) product category. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    product_categories_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) product category. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProductCategory"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProductCategory"];
                "multipart/form-data": components["schemas"]["PatchedProductCategory"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductCategory"];
                };
            };
        };
    };
    products_list: {
        parameters: {
            query?: {
                /** @description Les valeurs multiples doivent être séparées par des virgules. */
                category?: string[];
                created_at_max?: string;
                created_at_min?: string;
                is_active?: boolean;
                name?: string;
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
                /** @description Un numéro de page de l'ensemble des résultats. */
                page?: number;
                /** @description Nombre de résultats à retourner par page. */
                page_size?: number;
                /** @description Un terme de recherche. */
                search?: string;
                sku?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProductReadList"];
                };
            };
        };
    };
    products_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Product"];
                "application/x-www-form-urlencoded": components["schemas"]["Product"];
                "multipart/form-data": components["schemas"]["Product"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    products_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) product list view. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductRead"];
                };
            };
        };
    };
    products_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) product. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Product"];
                "application/x-www-form-urlencoded": components["schemas"]["Product"];
                "multipart/form-data": components["schemas"]["Product"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    products_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) product. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    products_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) product. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProduct"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProduct"];
                "multipart/form-data": components["schemas"]["PatchedProduct"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    roles_list: {
        parameters: {
            query?: {
                name?: string;
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
                /** @description Un numéro de page de l'ensemble des résultats. */
                page?: number;
                /** @description Nombre de résultats à retourner par page. */
                page_size?: number;
                /** @description Un terme de recherche. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRoleList"];
                };
            };
        };
    };
    roles_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Role"];
                "application/x-www-form-urlencoded": components["schemas"]["Role"];
                "multipart/form-data": components["schemas"]["Role"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
        };
    };
    roles_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) role. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
        };
    };
    roles_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) role. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Role"];
                "application/x-www-form-urlencoded": components["schemas"]["Role"];
                "multipart/form-data": components["schemas"]["Role"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
        };
    };
    roles_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) role. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    roles_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) role. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedRole"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedRole"];
                "multipart/form-data": components["schemas"]["PatchedRole"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
        };
    };
    token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    users_list: {
        parameters: {
            query?: {
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
                /** @description Un numéro de page de l'ensemble des résultats. */
                page?: number;
                /** @description Nombre de résultats à retourner par page. */
                page_size?: number;
                /** @description Les valeurs multiples doivent être séparées par des virgules. */
                roles?: string[];
                /** @description Un terme de recherche. */
                search?: string;
                username?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUserListList"];
                };
            };
        };
    };
    users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) user. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserList"];
                };
            };
        };
    };
    users_assign_role_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) user. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UserList"];
                "application/x-www-form-urlencoded": components["schemas"]["UserList"];
                "multipart/form-data": components["schemas"]["UserList"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserList"];
                };
            };
        };
    };
    users_remove_role_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) user. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UserList"];
                "application/x-www-form-urlencoded": components["schemas"]["UserList"];
                "multipart/form-data": components["schemas"]["UserList"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserList"];
                };
            };
        };
    };
    ventes_list: {
        parameters: {
            query?: {
                /** @description Les valeurs multiples doivent être séparées par des virgules. */
                currency?: string[];
                /** @description Les valeurs multiples doivent être séparées par des virgules. */
                customer?: string[];
                expected_delivery_date_max?: string;
                expected_delivery_date_min?: string;
                id?: string;
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
                /** @description Un numéro de page de l'ensemble des résultats. */
                page?: number;
                /** @description Nombre de résultats à retourner par page. */
                page_size?: number;
                /** @description Les valeurs multiples doivent être séparées par des virgules. */
                priority?: string[];
                /** @description Un terme de recherche. */
                search?: string;
                /** @description Les valeurs multiples doivent être séparées par des virgules. */
                status?: string[];
                total_max?: number;
                total_min?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedVenteReadList"];
                };
            };
        };
    };
    ventes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Vente"];
                "application/x-www-form-urlencoded": components["schemas"]["Vente"];
                "multipart/form-data": components["schemas"]["Vente"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vente"];
                };
            };
        };
    };
    ventes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) vente list view. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VenteRead"];
                };
            };
        };
    };
    ventes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) vente. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Vente"];
                "application/x-www-form-urlencoded": components["schemas"]["Vente"];
                "multipart/form-data": components["schemas"]["Vente"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vente"];
                };
            };
        };
    };
    ventes_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) vente. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ventes_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) vente. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedVente"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedVente"];
                "multipart/form-data": components["schemas"]["PatchedVente"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vente"];
                };
            };
        };
    };
    ventes_annuler_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) vente. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Vente"];
                "application/x-www-form-urlencoded": components["schemas"]["Vente"];
                "multipart/form-data": components["schemas"]["Vente"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vente"];
                };
            };
        };
    };
    ventes_valider_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur unique identifiant ce(cette) vente. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Vente"];
                "application/x-www-form-urlencoded": components["schemas"]["Vente"];
                "multipart/form-data": components["schemas"]["Vente"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vente"];
                };
            };
        };
    };
}
